# Generated by Django 4.1.13 on 2024-11-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0007_commentpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='name',
            new_name='username',
        ),
    ]
