# Generated by Django 4.1.13 on 2024-11-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0008_rename_name_commentpost_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
