# Generated by Django 4.1.13 on 2024-11-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
