# Generated by Django 4.1.13 on 2024-11-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
