# Generated by Django 4.1.13 on 2024-11-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0013_rename_text_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
