# Generated by Django 4.1.13 on 2024-11-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0015_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
