# Generated by Django 4.1.13 on 2024-11-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0016_rename_user_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
