# Generated by Django 4.1.13 on 2024-11-21 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0017_remove_comment_comment_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
