# Generated by Django 4.1.13 on 2024-11-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
