# Generated by Django 4.1.13 on 2024-11-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0024_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
