# Generated by Django 4.1.13 on 2024-11-21 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0025_remove_comment_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
